defaults:
- data: zarr
- dataloader: forecast_native_grid
- diagnostics: evaluation_ens
- system: example
- graph: multi_scale
- model: graphtransformer_ens
- task: temporal_downscaler
- training: ensemble
- override training/training_loss: ensemble_multiscale_aggregation
- _self_

config_validation: True

data:
  frequency: null
  datasets:
    data:
      forcing:
        - "cos_latitude"
        - "cos_longitude"
        - "sin_latitude"
        - "sin_longitude"
        - "cos_julian_day"
        - "cos_local_time"
        - "sin_julian_day"
        - "sin_local_time"
        - "insolation"
        - "lsm"
        - "z"
      processors:
        normalizer:
          config:
            max: ["z"]
            none:
              - "cos_latitude"
              - "cos_longitude"
              - "sin_latitude"
              - "sin_longitude"
              - "cos_julian_day"
              - "cos_local_time"
              - "sin_julian_day"
              - "sin_local_time"
              - "insolation"

dataloader:
  trajectory_sampling:
    stride: 6  # overlapping windows with stride 6 within each forecast
diagnostics:
  plot:
    callbacks: []
  callbacks: []

system:
  input:
    graph: graph_anemoi_new.pt
    loss_matrices_path: null
  hardware:
    accelerator: auto
    num_gpus_per_ensemble: 1
    num_gpus_per_node: 1
    num_nodes: 1
    num_gpus_per_model: 1

model:
  num_channels: 128

training:
  ensemble_size_per_device: 2
