---
defaults:
  - scalers: global
  - training_loss: single
  - optimization: default
  - weight_averaging: null

run_id: null
fork_run_id: null
transfer_learning: False
load_weights_only: False
update_ds_stats_on_ckpt_load:
  states: False
  tendencies: True

deterministic: False
precision: bf16-mixed
accum_grad_batches: 1
num_sanity_val_steps: 6

gradient_clip:
  val: 1.
  algorithm: norm

optimization:
  optimizer:
    _target_: torch.optim.AdamW
    weight_decay: 0.1
    betas: [0.9, 0.95]
    eps: 1e-7

method:
  _target_: anemoi.training.train.methods.TransportTraining
transport:
  prediction_mode: state
  objective: edm_diffusion

strategy:
  _target_: anemoi.training.distributed.strategy.DDPGroupStrategy
  num_gpus_per_model: ${system.hardware.num_gpus_per_model}
  read_group_size: ${dataloader.read_group_size}

loss_gradient_scaling: False

validation_metrics:
  datasets:
    data:
      mse:
        _target_: anemoi.training.losses.MSELoss
        scalers: ["node_weights", "time_steps"]
        ignore_nans: True

variable_groups:
  datasets:
    data:
      default: sfc
      pl:
        param: [q, t, u, v, w, z]

metrics:
  datasets:
    data:
      - z_500
      - t_850
      - u_850
      - v_850

max_epochs: null
max_steps: 1000000

submodules_to_freeze: []
recompile_limit: 32
