_target_: timm.scheduler.CosineLRScheduler
lr_min: 3e-7
t_initial: ${training.max_steps} # NOTE: When max_epochs < max_steps, scheduler will run for max_steps
warmup_t: 1000
t_in_epochs: false # t_initial and warmup_t are in steps, not epochs (matches interval: step)
