---
overwrite: True


nodes:
  # Data nodes
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.AnemoiDatasetNodes # options: AnemoiDatasetNodes, NPZFileNodes
      dataset: ${dataloader.training.datasets.data.dataset_config}
    attributes:
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.SphericalAreaWeights # options: Area, Uniform
        norm: unit-max # options: l1, l2, unit-max, unit-sum, unit-std
        fill_value: 0

edges: []

post_processors: []
